version: '3.8'
services:
  auditor:
    build: Auditor/
    container_name: auditor
    ports:
     - "12345:12345"
   
  jogador:
    build: Jogador/
    container_name: jogador
   
    depends_on:
      - auditor

  
